program ::= declaration program*

declaration ::= event | function | storage | contract


event ::= 'event' IDENTIFIER '{' field* '}'


function ::= 'function' method


storage ::= 'storage' IDENTIFIER storage_params? '{' object_body '}'

storage_params ::= '(' IDENTIFIER (',' IDENTIFIER)* ')'


contract ::= 'contract' IDENTIFIER '{' object_body '}'


object_body ::= (field | use | method)*


field ::= IDENTIFIER ':' type


use ::= 'use' IDENTIFIER '.' (IDENTIFIER | '*')


method ::= IDENTIFIER '(' method_params? ')' '{' statement* '}'

method_params ::= method_param (',' method_param)*

method_param ::= IDENTIFIER (':' type)?


type ::= IDENTIFIER type_params?

type_params ::= '(' type (',' type)* ')'


statement ::= ???
